### ISSUE TITLE
不使用latex如何运行这个demo

### ISSUE THREAD

**Issue by ftry** [metahouses/-PhySO-#2]
FileNotFoundError: [Errno 2] No such file or directory: 'latex'

The above exception was the direct cause of the following exception:

RuntimeError: Failed to process string with tex because latex could not be found

如何解决这个问题：不使用latex。我想在服务器上训练这个过程，不需要实时显示图片，也不想使用latex！

**Comment by ftry** [comment]
解决了问题！如下：sudo yum install texlive texlive-dvipng

**Comment by wtestererer** [comment]
其实只要加一句
import matplotlib as mpl
mpl.rcParams.update(mpl.rcParamsDefault)
